/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.HoaDonChiTiet;
import service.HoaDonChiTietService;
import service.HoaDonService;

/**
 *
 * @author thaitv
 */
public class ViewHoaDon extends javax.swing.JFrame {

    private HoaDonService service = new HoaDonService();
    private HoaDonChiTietService hdctService = new HoaDonChiTietService();
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form ViewHoaDon
     */
    public ViewHoaDon() {
        initComponents();
        loadHoaDon();
        loadHoaDonChiTiet();
        rdTatCa.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rdTatCa = new javax.swing.JRadioButton();
        rdDaThanhToan = new javax.swing.JRadioButton();
        rdChoThanhToan = new javax.swing.JRadioButton();
        rdDaHuy = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        txtISearchdHoaDon = new javax.swing.JTextField();
        txtSearchByIdSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        txtTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Id", "Id KH", "Id Voucher", "Id NV", "So luong", "Tong tien", "Giam gia", "Ngay tao", "Nguoi tao", "Trang thai"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Id San pham", "Ten SP", "Gia", "So luong", "Tong tien", "Giam gia", "Thanh tien"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDonChiTiet);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng thái"));

        buttonGroup1.add(rdTatCa);
        rdTatCa.setText("Tất cả");
        rdTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTatCaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdDaThanhToan);
        rdDaThanhToan.setText("Đã thanh toán");
        rdDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDaThanhToanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdChoThanhToan);
        rdChoThanhToan.setText("Chờ thanh toán");
        rdChoThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdChoThanhToanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdDaHuy);
        rdDaHuy.setText("Đã hủy");
        rdDaHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDaHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdDaThanhToan)
                .addGap(53, 53, 53)
                .addComponent(rdChoThanhToan)
                .addGap(64, 64, 64)
                .addComponent(rdDaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTatCa)
                    .addComponent(rdDaThanhToan)
                    .addComponent(rdChoThanhToan)
                    .addComponent(rdDaHuy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng điều khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Tìm theo ID SP:");

        jLabel2.setText("Tìm theo ID Hóa đơn:");

        jdcNgayBatDau.setDateFormatString("yyyy-MM-dd");

        txtISearchdHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtISearchdHoaDonKeyReleased(evt);
            }
        });

        txtSearchByIdSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchByIdSPKeyReleased(evt);
            }
        });

        jLabel3.setText("Ngày bắt đầu:");

        jLabel4.setText("Ngày kết thúc:");

        jdcNgayKetThuc.setDateFormatString("yyyy-MM-dd");

        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtISearchdHoaDon)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchByIdSP)
                    .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtISearchdHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchByIdSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTimKiem))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int index = tblHoaDon.getSelectedRow();
        int idHoaDon = (int) tblHoaDon.getValueAt(index, 1);
        hdctService.mouseClicked(idHoaDon);
        loadHDAndHDCT(idHoaDon);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void rdTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTatCaActionPerformed
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.loadDataHoaDon()) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getThanhTien(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }//GEN-LAST:event_rdTatCaActionPerformed

    private void rdDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDaThanhToanActionPerformed
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.daThanhToan()) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getThanhTien(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }//GEN-LAST:event_rdDaThanhToanActionPerformed

    private void rdChoThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdChoThanhToanActionPerformed
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.choThanhToan()) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getThanhTien(), hd.getNgayTao(), hd.getNgayTao(), hd.getTrangThai()
            });
        }
    }//GEN-LAST:event_rdChoThanhToanActionPerformed

    private void rdDaHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDaHuyActionPerformed
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.daHuy()) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getThanhTien(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }//GEN-LAST:event_rdDaHuyActionPerformed

    private void txtISearchdHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISearchdHoaDonKeyReleased
        Integer id = Integer.parseInt(txtISearchdHoaDon.getText());
        service.timKiemHoaDon(id);
        service.loadHoaDonandHDCT(id);
        timKiemHoaDon(id);
        loadHDAndHDCT(id);
    }//GEN-LAST:event_txtISearchdHoaDonKeyReleased

    private void txtSearchByIdSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchByIdSPKeyReleased
        Integer idSP = Integer.parseInt(txtSearchByIdSP.getText());
        hdctService.findSPCTAndHDCT(idSP);
        findSPCTAndHDCT(idSP);
    }//GEN-LAST:event_txtSearchByIdSPKeyReleased

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        Date bd = jdcNgayBatDau.getDate();
        Date kt = jdcNgayKetThuc.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(bd);
        Calendar calendar1 = Calendar.getInstance();
        calendar1.setTime(kt);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBatDau = dateFormat.format(bd);
        String ngayKetThuc = dateFormat.format(kt);
        if (bd.after(kt)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu");
            return;
        }
            if (ngayBatDau != null && ngayKetThuc == null) {
                service.loadNgayStart(ngayBatDau);
                loadNgayBatDau(ngayBatDau);
            } else if (ngayBatDau == null && ngayKetThuc != null) {
                service.loadNgayEnd(ngayKetThuc);
                loadNgayKetThuc(ngayKetThuc);
            } else {
                service.timKiemTheoNgayThang(ngayBatDau, ngayKetThuc);
                loadTimKiemTheoNgay(ngayBatDau, ngayKetThuc);
            }
    }//GEN-LAST:event_txtTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JRadioButton rdChoThanhToan;
    private javax.swing.JRadioButton rdDaHuy;
    private javax.swing.JRadioButton rdDaThanhToan;
    private javax.swing.JRadioButton rdTatCa;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTextField txtISearchdHoaDon;
    private javax.swing.JTextField txtSearchByIdSP;
    private javax.swing.JButton txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadHoaDon() {
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.loadDataHoaDon()) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }

    private void loadHoaDonChiTiet() {
        defaultTableModel = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDonChiTiet hdct : hdctService.loadHDCT()) {
            defaultTableModel.addRow(new Object[]{
                i++, hdct.getIdSanPham(), hdct.getTenSP(), hdct.getGia(), hdct.getSoLuong(),
                hdct.getTongTien(), hdct.getGiaGiam(), hdct.getThanhTien()
            });
        }
    }

    private void loadHDAndHDCT(int idHoaDon) {
        defaultTableModel = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDonChiTiet hdct : hdctService.loadHDAndHDCT(idHoaDon)) {
            defaultTableModel.addRow(new Object[]{
                i++, hdct.getIdSanPham(), hdct.getTenSP(), hdct.getGia(), hdct.getSoLuong(),
                hdct.getTongTien(), hdct.getGiaGiam(), hdct.getThanhTien()
            });
        }
    }

//    private void searchByIdHD() {
//        Integer id = Integer.parseInt(txtSearchByIDHD.getText());
//        service.searchById(id);
//    }
    private void loadSearchIDHD(int id) {
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.searchById(id)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getThanhTien(), hd.getNgayTao(), hd.getNgayTao(), hd.getTrangThai()
            });
        }
    }
    
    void loadTimKiemHoaDon(int id){
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;
        for (HoaDon hd : service.timKiemHoaDon(id)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }
    
    void loadSearchHDCT(int id){
        defaultTableModel = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;
        
        for (HoaDonChiTiet hdct : hdctService.searchHoaDonChiTiet(id)) {
            defaultTableModel.addRow(new Object[]{
                i++, hdct.getIdSanPham(), hdct.getTenSP(), hdct.getGia(), hdct.getSoLuong(),
                hdct.getTongTien(), hdct.getGiaGiam(), hdct.getThanhTien()
            });
        }
    }
    
    void timKiemHoaDon(int id){
         defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.timKiemHoaDon(id)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }
    
    void findSPCTAndHDCT(int idSanPham){
        defaultTableModel = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDonChiTiet hdct : hdctService.searchHoaDonChiTiet(idSanPham)) {
            defaultTableModel.addRow(new Object[]{
                i++, hdct.getIdSanPham(), hdct.getTenSP(), hdct.getGia(), hdct.getSoLuong(),
                hdct.getTongTien(), hdct.getGiaGiam(), hdct.getThanhTien()
            });
        }
    }
    
    void loadNgayBatDau(String ngayBatDau){
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.loadNgayStart(ngayBatDau)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }
    
     void loadNgayKetThuc(String ngayKetThuc){
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.loadNgayEnd(ngayKetThuc)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }
     
    void loadTimKiemTheoNgay(String bd, String kt){
        defaultTableModel = (DefaultTableModel) tblHoaDon.getModel();
        defaultTableModel.setRowCount(0);
        int i = 1;

        for (HoaDon hd : service.timKiemTheoNgayThang(bd, kt)) {
            defaultTableModel.addRow(new Object[]{
                i++, hd.getId(), hd.getIdKH(), hd.getIdVoucher(), hd.getIdNV(), hd.getSoLuong(),
                hd.getTongTien(), hd.getGiamGia(), hd.getNgayTao(), hd.getNguoiTao(), hd.getTrangThai()
            });
        }
    }
}
